### ISSUE TITLE
Module Name

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/gofer#9]
We need a better name than `filesystem`!

**Comment by foolmoron** [comment]
jetsystem
gnatsystem
beesystem (sponsored by Bee Movie 2 featuring Jerry Seinfeld)
filey
nodesystem
flysystem.js (might as well)
YANFS (yet another...)

**Comment by togakangaroo** [comment]
* file-clerk
* file-room
* gimmie
* give-and-take
* glamping (I don't know why, it just sounds like a good library name)

**Comment by foolmoron** [comment]
doppel-fs
file-doppel
juxtapose-fs

**Comment by sohail-surge** [comment]
pollock-fs (abstract, get it)

**Comment by CWSpear** [comment]
@sohail-surge I don't

**Comment by CWSpear** [comment]
What about Warehouse? `warehouse-fs`, maybe?

**Comment by dylan-surge** [comment]
transponder-fs

**Comment by dylan-surge** [comment]
travers-fs

**Comment by dylan-surge** [comment]
transparent-fs

**Comment by dylan-surge** [comment]
trans-fs

**Comment by CWSpear** [comment]
For those of you with access to our Slack, I've been wanting to name a project CONTRA for a long time:

https://surgellc.slack.com/archives/developers/p1424225539000000

COntra is 
Not 
Technically a 
Recursive 
Acronym

**Comment by foolmoron** [comment]
@dylan-surge trans-fat?

**Comment by togakangaroo** [comment]
Well in that case I propose fster

**Comment by dylan-surge** [comment]
@foolmoron - yes, I thought so too...if it were an API for FAT32 specifically it'd be perfect :)

**Comment by RipRyness** [comment]
getrdone
justdoit
filecrud
filecruddy
anyfilecrud
everyfile
everyfilecrud

**Comment by CWSpear** [comment]
`gofer`

gofer this file, gofer that file...

**Comment by RipRyness** [comment]
make gopher great again :)
https://www.minnpost.com/business/2016/08/rise-and-fall-gopher-protocol

**Comment by foolmoron** [comment]
Although the name has already been taken by a few things
https://www.google.com/search?q=gofer+npm

**Comment by CWSpear** [comment]
`gofer-fs`

**Comment by CWSpear** [comment]
https://www.npmjs.com/package/gofer-fs
